# reward-interval in seconds, must reload plugin to take effect
reward_interval: 10

# reward-cap is the maximum amount of money that can be earned in a single interval
reward_cap: 100000

# reward-base-amount is the amount of money that is earned every interval, before any multipliers
reward_base_amount: 2000

# session expire in seconds
session_expire: 5